[theme]

primaryColor = "#f63366"
# backgroundColor = "#10344b"
backgroundColor = "#081028"
# secondaryBackgroundColor = "#154360"
secondaryBackgroundColor = "#0B1739"
textColor = "#fafafa"
font = "sans serif"

[server]
enableStaticServing = true